
eureka:
  client:
    register-with-eureka: true  #是否像服务中心注册自己
    fetch-registry: true #是否检索服务（自己是注册中心不需要检索）
    service-url: #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；
      defaultZone: http://127.0.0.1:9091/eureka,http://127.0.0.1:9092/eureka

